# Generated by Django 6.0.1 on 2026-01-26 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_conversation_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='base.directmessage'),
        ),
    ]
