# Generated by Django 6.0.1 on 2026-01-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_directmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='file_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('voice', 'Voice')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='voice_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds for voice messages', null=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
