# Generated by Django 6.0.1 on 2026-01-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_directmessage_file_directmessage_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original file name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='file_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('voice', 'Voice'), ('document', 'Document')], default='text', max_length=10),
        ),
    ]
